language: node_js
node_js:
  - "8"
  - "10"
  - "12"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2842d858f1da3ba1f054
    on_success: change
    on_failure: always
    on_start: never
